<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Password_pf-c-button pf-m-control</name>
   <tag></tag>
   <elementGuidId>3380a616-c5d6-4537-8fa0-a19ce2275647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.pf-c-button.pf-m-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de9dbef3-dd1a-4e29-aa8b-835ba8f799bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pf-c-button pf-m-control</value>
      <webElementGuid>bb1a2d03-1130-4839-aa67-707fea3d5790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d00297ff-991f-429f-a645-de99afc7db46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show password</value>
      <webElementGuid>6e3377ff-bf93-4a82-bdb4-7905e984e865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1fd0fe38-d665-4a4b-9dc5-a2cae50779d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-show</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>91381ea3-95fc-4bbe-9378-080e2905cf37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-hide</name>
      <type>Main</type>
      <value>fa fa-eye-slash</value>
      <webElementGuid>5cd2f344-ee37-45e5-ad11-8e249da8c92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-show</name>
      <type>Main</type>
      <value>Show password</value>
      <webElementGuid>a6f5ea86-5a3b-4057-b3c2-ae02f04b83c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-hide</name>
      <type>Main</type>
      <value>Hide password</value>
      <webElementGuid>dc64c27b-c8bb-4220-b2c8-8d9c9cc3bccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-form-login&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;pf-c-input-group&quot;]/button[@class=&quot;pf-c-button pf-m-control&quot;]</value>
      <webElementGuid>67267b14-2bcf-41f5-93ce-d1d9b6824f4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>df9b5c3f-1f59-4a16-b540-b1badc38db4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login']/div[2]/div/button</value>
      <webElementGuid>5496f1d5-789e-47f4-ba58-7b25eecbb2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>394f7343-752f-45fd-845a-d2766047acf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>a44d1280-3862-4675-8b66-4e69558fd444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>94e989ce-7f22-4881-b67f-ece4a153f15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a84b57cb-1b52-4e56-b5bd-0a391fbfb15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>052209a0-ae65-401e-9e30-4b4c41931956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
