<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>3850024f-f841-40bc-87f2-0161761bd619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.logout-btn > span.menu-text.mob-hide</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/ul/li[7]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b1a68d9-866e-4ed1-b897-fdf45c87ab7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text mob-hide</value>
      <webElementGuid>ef94ecb9-cc5b-4ac6-8c05-1541d4ae965d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>65891e5f-cd46-45d8-ba45-3530aea0af85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App has-header&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;header-wrap&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;navigation&quot;]/li[7]/button[@class=&quot;logout-btn&quot;]/span[@class=&quot;menu-text mob-hide&quot;]</value>
      <webElementGuid>8912c62d-215d-4da0-a99a-aa59ccef0ac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/ul/li[7]/button/span</value>
      <webElementGuid>5cfa8236-a1c5-4765-80b2-7f36d3704c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::span[1]</value>
      <webElementGuid>cbdb8c01-45be-4615-beed-9d5c373cd437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/following::span[2]</value>
      <webElementGuid>54ea4bf2-6266-482e-b4d2-4d1c3dfe4c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Card'])[1]/preceding::span[1]</value>
      <webElementGuid>f7c40193-b458-422f-a73c-040e4876806e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>38ec3caf-3819-466e-83a0-44e37d643521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>1eb14b03-f4c0-4d27-8b06-12017cb05c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>5c63c531-9cfe-4eee-8d14-a443bea764af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
